print("name")
print("age")
print("roll num")
print("class")
print("collage name")
print("group")
print("suzenkumarmohanty")
print("19")
print("21co29")
print("computer science and engineering")
print("balasore school of engineering")
print("11")